# Generated by Django 4.2 on 2024-05-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_buy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buy',
        ),
    ]
